The ``add_integer`` module
===================================

Using ``add_integer``
-------------------------------------------------------

import function_name from module_name
    >>> add_integer = __import__('0-add_integer').add_integer
 
    >>> add_integer(8, 2)
    10

    >>> add_integer(-8, 8)
    0

    >>> add_integer(8, -8)
    0

    >>> add_integer(-8, -8)
    -16

    >>> add_integer(3.8, 1.2)
    4

    >>> add_integer(10.3, -2)
    8

    >>> add_integer(-2, 10.3)
    8

    >>> add_integer(45)
    143

    >>> add_integer(-True, False)
    -1

    >>> add_integer(-True, -False)
    -1

    >>> add_integer(True, False)
    1

    >>> add_integer(True, -False)
    1

    >>> add_integer(False, False)
    0

    >>> add_integer(10, True)
    11

    >>> add_integer(10, False)
    10

    >>> add_integer("25", 25)
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> add_integer(25, "25")
    Traceback (most recent call last):
    TypeError: b must be an integer

    >>> add_integer()
    Traceback (most recent call last):
    TypeError: add_integer() missing 1 required positional argument: 'a'

    >>> add_integer(None)
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> add_integer(None, "HOLA")
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> add_integer("HOLA", None)
    Traceback (most recent call last):
    TypeError: b must be an integer

    >>> add_integer(None, 47)
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> add_integer(47, None)
    Traceback (most recent call last):
    TypeError: b must be an integer

    >>> add_integer("HOLA")
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> print(add_integer("HOLA", "HOLA"))
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> add_integer("HOLA", 23)
    Traceback (most recent call last):
    TypeError: a must be an integer

    >>> add_integer(23, "HOLA")
    Traceback (most recent call last):
    TypeError: b must be an integer

    >>> add_integer(float('inf'))
    Traceback (most recent call last):
    OverflowError: cannot convert float infinity to integer

    >>> add_integer(18, float("inf"))
    Traceback (most recent call last):
    OverflowError: cannot convert float infinity to integer

    >>> add_integer(float('inf'), 18)
    Traceback (most recent call last):
    OverflowError: cannot convert float infinity to integer

    >>> add_integer(float('NaN'))
    Traceback (most recent call last):
    ValueError: cannot convert float NaN to integer

    >>> add_integer(float("NaN"), 45)
    Traceback (most recent call last):
    ValueError: cannot convert float NaN to integer

    >>> add_integer(45, float("NaN"))
    Traceback (most recent call last):
    ValueError: cannot convert float NaN to integer

    >>> add_integer(23, 19, 45)
    Traceback (most recent call last):
    TypeError: add_integer() takes from 1 to 2 positional arguments but 3 were given
